# .readthedocs.yml
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"  # Specify the Python version

python:
  install:
    - requirements: docs/requirements.txt  # Install dependencies from requirements.txt
    # Install our python package before building the docs
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py  # Path to your Sphinx configuration file
